services:
  postgres:
    image: postgres:18-alpine
    restart: always
    container_name: rxwod-postgres
    environment:
      POSTGRES_USER: rxwod
      POSTGRES_PASSWORD: rxwod
      POSTGRES_DB: rxwod
    ports:
      - "5429:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rxwod -d rxwod"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
